@startuml

title: <size:20> PUT Request [Process Sequence]</size>

participant Client as cl <<HTTP>>
participant Serializer as s <<ASP.NET>>
participant RoutingMechanism as r <<ASP.NET>>
participant APIController as c <<Controller>>
participant APIModel as m <<Model>>

database database as db

cl -> r : [PUT] request

activate r
r -> c : put(id, object)
deactivate r
activate c

note right of s
 response as 
 JSON, XML, etc..
end note

c -> s : deserialize

s --> c : return object

note right of c 
 **<color purple>CRUD</color>**
end note

c -> m : update(object)

note right of m
 **<color blue>Entity</color>**
 **<color blue>Framework</color>**
end note

activate m
m -> db : update(object)
deactivate m
activate db
db--> c : DB Response
deactivate db

c --> cl : NoContent()
deactivate c

@enduml