@startuml

title: <size:20> DELETE Request [Process Sequence]</size>

participant Client as cl <<HTTP>>
participant Serializer as s <<ASP.NET>>
participant RoutingMechanism as r <<ASP.NET>>
participant APIController as c <<Controller>>
participant APIModel as m <<Model>>

database database as db

cl -> r : [DELETE] request

activate r
r -> c : delete(id)
deactivate r
activate c

note right of s
 response as 
 JSON, XML, etc..
end note

c -> s : deserialize

s --> c : return object

c -> m : read(id)

activate m
m -> db : bind(id)
db --> m : returns object
m --> c : returns object

note right of c 
 **<color purple>CRUD</color>**
end note

c -> m : delete(object)

note right of m
 **<color blue>Entity</color>**
 **<color blue>Framework</color>**
end note

m -> db : delete(object)
deactivate m
activate db
db--> c : DB Response
deactivate db

c --> cl : ok(object) [200 ok]
deactivate c

@enduml