@startuml

title: <size:20> GET Request [Process Sequence]</size>

participant Client as cl <<HTTP>>
participant Serializer as s <<ASP.NET>>
participant RoutingMechanism as r <<ASP.NET>>
participant APIController as c <<Controller>>
participant APIModel as m <<Model>>

database database as db

cl -> r : [GET] request

activate r
r -> c : get()
deactivate r

note right of c 
 **<color purple>CRUD</color>**
end note

activate c
c -> m : read()

note right of m
 **<color blue>Entity</color>**
 **<color blue>Framework</color>**
end note

activate m
m -> db : bind()
activate db
db --> m : returns\nobject(s) 
deactivate db
m --> c : returns object(s)
deactivate m

create "dto : ResponseDTO" as dto <<DTO>>
c -> dto : new() : dto
c --> s : ok(dto) : TaskAction
deactivate c

note right of cl
 response as 
 JSON, XML, etc..
end note

activate s
s --> cl : HTTP Response
deactivate s

'' DTO


@enduml