@startuml

title: <size:20>API Overview</size>

agent HTTP as h
note left : Client

interface "RESTful API" as i <<interface>>
h ---( i : consume

file Serialization
note right : DTO Structure
Serialization -- i : ex. JSON, XML, etc..

component "Medicines BackOffice" as m
m ---( i : consume
node server
m -> server

component "Receipts BackOffice" as r
r ---( i 
r --> server

node "Medicines BackOffice Overview" as zoom {

    component Controller as c
    component Model as md
    component DTO as d
    component View as v
    database database as db

    c -( md
    c --( d
    c --( v
    c --( db

    v -( d

}

m --^ zoom : ZOOM OVERVIEW

@enduml