@startuml

rectangle "1st Iteration" #009FBD {
    package "Backend Medicines" as BM {
    }
}

rectangle "2nd Iteration" #43CC72 {
    package "Frontend Medical Receipts" as BR {
    }
}

rectangle "3rd Iteration" #33AF39 {
    package "Frontend Electronic Prescriptions" as FEP {
    }
}

BM <... BR
BM <. FEP
BR <. FEP

@enduml