@startuml UCD.puml

actor :Physician: as D
actor :Pharmacist: as F
actor :System: as S
actor :Patient: as P
actor :Anonymous: as A

usecase (Create receipts) as crr
usecase (Edit receipts) as er
usecase (Consult receipts) as cr
usecase (Consult prescriptions) as cp
usecase (Fill prescriptions) as fp
usecase (Alert patients\nwith new receipts) as ap
usecase (Register as patient) as ru
usecase (Authenticate \nuser) as auth
usecase (List presentation) as lp
usecase (Comment \npresentation) as comp
usecase (Consult posologies) as consp
usecase (Alter patient for the \nexpiration date proximity) as alp

S -> ap
D -> crr
D -> er
D -> cr
D -> cp
F -> cr
F -> cp
F -> fp
P --> cr
P -> cp
A ---> ru
A --> auth
lp <- A
D ---> comp
consp <- P
S -> alp


S --[hidden]> D
D -[hidden]> F
F --[hidden]> P



@enduml

DM <- F
D -> CM
D --> PM
APEP <-S
OD <- P
CP <- P

' Just for display purposes
I --[hidden]> D
F --[hidden]> S
S --[hidden]> P