@startuml

title: <size:20> DELETE Request [Process View]</size>

' Lifelines
participant Client as cl <<HTTP>>
participant Server as node <<NodeJS>>
participant App as app <<ExpressJS>>
participant Router as r <<ExpressJS>>
collections Middlewares as mds <<ExpressJS>>
participant Controller as c <<Controller>>
participant Model as m <<Mongoose>>
database Database as db <<MongoDB>>


' Sequence
cl -> node : [DELETE] request
activate node #6cc24a

node -> app : use()
    activate app
    app -> r : delete()
        activate r
            loop use middlewares
            r -> mds : use()
            activate mds
                mds -> mds : [perform task]
                mds -> r : next() [callback]
                activate r
                r --> mds
                deactivate r
            end
            deactivate mds
            r -> c : deleteObject()
            activate c
                c -> m : delete()
                activate m
                    note right of m
                     **<color purple>CRUD</color>**
                    end note
                    m -> db : delete from database
                    db --> m : return success info
                    m --> c
                deactivate m
                c --> r
            deactivate c
            r --> app
        deactivate r
        app --> node
    deactivate app
    node --> cl : display success message <font color=green><b>[status: 201]
deactivate node

@enduml